(function(){
'use strict';
const P=window.POKER_BRAIN_PACK||{exact:{},preflop:{},postflop:[],reviews:{},concepts:{},stats:{}};
const R='AKQJT98765432';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function normAction(a=''){a=String(a).toUpperCase().trim();if(/ФОЛД|FOLD/.test(a))return'FOLD';if(/КОЛЛ|CALL/.test(a))return'CALL';if(/ЧЕК|CHECK/.test(a))return'CHECK';if(/СТАВ|BET/.test(a))return'BET';if(/3-БЕТ|3BET|5-БЕТ|5BET|РЕЙЗ|RAISE/.test(a))return'RAISE';return a}
function classOf(cards=[]){if(cards.length<2)return null;const a=cards[0][0],b=cards[1][0],ia=R.indexOf(a),ib=R.indexOf(b);if(ia<0||ib<0)return null;if(a===b)return a+a;const suited=cards[0].slice(1)===cards[1].slice(1);return ia<ib?a+b+(suited?'s':'o'):b+a+(suited?'s':'o')}
function baseId(id=''){return String(id).replace(/_V\d+$/,'')}
function nearest(v,arr){return arr.reduce((a,b)=>Math.abs(b-v)<Math.abs(a-v)?b:a,arr[0])}
function ctxFromText(t=''){const x=String(t).toLowerCase();if(/125%|140%|150%|100%|overbet/.test(x))return'FACE_BIG';if(/75%|80%|66%|50%/.test(x))return'FACE_MEDIUM';if(/25%|33%|small|малень/.test(x))return'FACE_SMALL';return'CHECKED_TO'}
function boardArch(board=[]){if(board.length<3)return'LOW_DRY';const rv=c=>R.indexOf(c[0]);const ranks=board.map(c=>rv(c)).sort((a,b)=>a-b),suits=board.map(c=>c.slice(1));const uniq=new Set(ranks),paired=uniq.size<ranks.length;const suitCounts={};suits.forEach(s=>suitCounts[s]=(suitCounts[s]||0)+1);const maxSuit=Math.max(...Object.values(suitCounts));const gaps=[];const u=[...uniq].sort((a,b)=>a-b);for(let i=1;i<u.length;i++)gaps.push(u[i]-u[i-1]);const connected=gaps.some(g=>g<=1)||gaps.filter(g=>g<=2).length>=2;const hi=ranks[0];if(maxSuit>=3)return'MONOTONE';if(board.length===5&&u.length>=4&&Math.max(...u)-Math.min(...u)<=4)return'FOUR_STRAIGHT';if(paired)return'PAIRED_DRY';if(connected&&maxSuit>=2)return'TWO_TONE_DYNAMIC';if(connected)return'DYNAMIC_CONNECTED';if(hi<=1)return'A_HIGH_DRY';if(hi<=2)return'K_HIGH_DRY';if(hi<=4)return'HIGH_CONNECTED';return'LOW_DRY'}
function handBucket(hero=[],board=[]){if(hero.length<2)return'AIR';const ranks=c=>R.indexOf(c[0]);const br=board.map(ranks),hr=hero.map(ranks);const counts={};[...br,...hr].forEach(x=>counts[x]=(counts[x]||0)+1);const heroPair=hero[0][0]===hero[1][0];let pairBoard=hr.some(x=>br.includes(x));const all=[...br,...hr];const maxCount=Math.max(...Object.values(counts));if(maxCount>=4)return'NUTTED';if(maxCount>=3)return'TWO_PAIR_PLUS';let pairs=Object.values(counts).filter(n=>n>=2).length;if(pairs>=2)return'TWO_PAIR_PLUS';if(heroPair){const highestBoard=Math.min(...br);if(Math.max(...hr)<highestBoard)return'OVERPAIR';return'MIDDLE_PAIR'}if(pairBoard){const hit=Math.min(...hr.filter(x=>br.includes(x)));const top=Math.min(...br);return hit===top?'TOP_PAIR':'MIDDLE_PAIR'}
const suitCount={};[...hero,...board].forEach(c=>{const s=c.slice(1);suitCount[s]=(suitCount[s]||0)+1});const fd=board.length<5&&Object.values(suitCount).some(n=>n===4);const vals=[...new Set(all)].sort((a,b)=>a-b);let sd=false;for(let i=0;i<vals.length;i++)for(let j=i+1;j<vals.length;j++)for(let k=j+1;k<vals.length;k++)if(vals[k]-vals[i]<=4)sd=true;if(fd&&sd)return'COMBO_DRAW';if(fd||sd)return'DRAW';if(hr.every(x=>x<Math.min(...br)))return'OVERCARDS';return'AIR'}
function preflopLookup(spot){const hc=classOf(spot.hero||[]);if(!hc)return null;const stack=nearest(Number(spot.stack||spot.effStack||30),[20,25,30,40,50]);const pos=String(spot.pos||spot.heroSeat||'BTN').split(/\s|vs/i)[0].toUpperCase();const text=String(spot.ctx||'');let key=null;if(/сфолдили|unopened|first in/i.test(text))key=`RFI|${pos}|${stack}|${hc}`;else if(pos==='BB'&&/open|открыл/i.test(text)){const m=text.match(/(UTG|HJ|CO|BTN|SB)/i);key=`BB_DEFEND|${(m?m[1]:'BTN').toUpperCase()}|${stack}|${hc}`}else if(/4-bet|4bet|3-бет|3bet/i.test(text))key=`VS_3BET|${pos}|${stack}|${hc}`;else if(/open|открыл/i.test(text)){const m=text.match(/(UTG|HJ|CO|BTN|SB)/i);key=`VS_OPEN|${pos}|${(m?m[1]:'CO').toUpperCase()}|${stack}|${hc}`}
const actions=key&&P.preflop[key];return actions?{actions,concept:'preflop.generic',why:'Policy взята из локального preflop atlas с учётом позиции, стека и класса руки.',source:'PREFLOP_ATLAS',confidence:82}:null}
function genericPostflop(spot){const street=String(spot.street||'FLOP').toUpperCase().replace('ФЛОП','FLOP').replace('ТЁРН','TURN').replace('РИВЕР','RIVER');const arch=boardArch(spot.board||[]),bucket=handBucket(spot.hero||[],spot.board||[]),ip=!/BB|SB/.test(String(spot.pos||spot.heroSeat||''));const ctx=ctxFromText(spot.ctx||'');let rows=P.postflop.filter(x=>x.street===street&&x.arch===arch&&x.bucket===bucket&&x.ip===ip&&x.ctx===ctx);if(!rows.length)rows=P.postflop.filter(x=>x.street===street&&x.bucket===bucket&&x.ctx===ctx);const row=rows[0];if(!row)return null;return{actions:row.actions,sizes:row.sizes,concept:`postflop.${street.toLowerCase()}.${arch.toLowerCase()}`,why:`Модель учитывает ${arch.toLowerCase().replaceAll('_',' ')}, hand bucket ${bucket.toLowerCase().replaceAll('_',' ')}, позицию и тип давления.`,source:'POSTFLOP_ATLAS',confidence:68,features:{arch,bucket,ctx}}}
function nodeFor(spot){const id=baseId(spot.spotId||spot.id||'');let n=P.exact[id];if(!n&&spot.theme)n=P.exact['DAILY:'+spot.theme];if(n)return{...n,source:'EXACT_REFERENCE_NODE',confidence:94};return preflopLookup(spot)||genericPostflop(spot)}
function gradeFromFreq(freq,max){if(max<=0)return'r';const rel=freq/max;if(freq>=.5||rel>=.78)return'g';if(freq>=.15||rel>=.28)return'y';return'r'}
function sizeEval(size,sizes=[]){if(size==null||!sizes?.length)return{grade:null,fit:null,best:null};let best={fit:-1,pct:null,weight:0,dist:999};for(const s of sizes){const dist=Math.abs(Number(size)-s.pct),fit=s.weight*Math.exp(-(dist*dist)/(2*18*18));if(fit>best.fit)best={fit,pct:s.pct,weight:s.weight,dist}}const grade=best.dist<=12||best.fit>=.32?'g':best.dist<=28||best.fit>=.10?'y':'r';return{grade,fit:best.fit,best:best.pct,dist:best.dist}}
function riverMath(spot){const t=String(spot.ctx||'');const m=t.match(/(\d+(?:\.\d+)?)%/);const pct=m?Number(m[1]):null;const pot=Number(spot.pot||0);if(!pct||!pot)return null;const bet=pot*pct/100;const req=bet/(pot+2*bet);const mdf=pot/(pot+bet);const bluffPerValue=bet/(pot+bet);return{betPct:pct,bet:bet,requiredEquity:req*100,mdf:mdf*100,bluffPerValue}}
function gradeDecision(spot,action,size=null){const node=nodeFor(spot)||{actions:{},why:'Для этого узла пока нет модели.',source:'NO_MODEL',confidence:0};const a=normAction(action);const entries=Object.entries(node.actions||{});const max=entries.length?Math.max(...entries.map(x=>x[1])):0;const freq=Number(node.actions?.[a]||0);const ag=gradeFromFreq(freq,max);const se=sizeEval(size,node.sizes||[]);const grade=ag==='r'||se.grade==='r'?'r':ag==='y'||se.grade==='y'?'y':'g';const top=entries.sort((x,y)=>y[1]-x[1]).slice(0,3).map(([k,v])=>({action:k,freq:v}));const alt=top.find(x=>x.action!==a);const actionRel=max?freq/max:0;const sizeRel=se.grade==null?1:(se.grade==='g'?1:(se.grade==='y'?0.62:0.18));const score=Math.round(100*(.72*actionRel+.28*sizeRel));return{grade,actionGrade:ag,sizeGrade:se.grade,action:a,actionFrequency:freq,topActions:top,sizeBest:se.best,sizeDistance:se.dist,score,concept:node.concept||'unknown',explanation:node.why||'',source:node.source,confidence:node.confidence||0,alternative:alt,river:riverMath(spot),features:node.features||null,modelVersion:P.version}}
function reviewLine(Rv){const m=P.reviews?.[Rv.id];if(!m)return{clean:false,culpritIndex:Rv.bad,losses:[],why:Rv.why,confidence:40,source:'FALLBACK'};return{clean:m.clean,culpritIndex:m.culprit,losses:m.losses,why:m.why,concept:m.concept,confidence:92,source:'LINE_MODEL'}}
function gradeRepair(Rv,value){const m=P.reviews?.[Rv.id];if(!m)return{grade:'y',fit:0};const entries=Object.entries(m.repair||{}).map(([k,v])=>({size:k==='CHECK'?0:Number(k),w:Number(v)}));if(!entries.length)return{grade:'g',fit:1};let best={w:-1,size:null,fit:-1};for(const e of entries){const d=Math.abs(Number(value)-e.size),fit=e.w*Math.exp(-(d*d)/(2*14*14));if(fit>best.fit)best={...e,fit}}return{grade:best.fit>=.45?'g':best.fit>=.12?'y':'r',fit:best.fit,bestSize:best.size,source:'REPAIR_MODEL'}}
function conceptLabel(id){return P.concepts?.[id]?.label||String(id||'').replaceAll('.',' · ').toUpperCase()}
function courseForConcept(id){return P.concepts?.[id]?.course||null}
function analyzeHand(h){const heroActs=(h.actions||[]).filter(a=>a.actor==='HERO');const last=heroActs.at(-1);if(!last)return{match:'NO_DECISION',confidence:0,summary:'Добавь хотя бы одно действие Hero — без точки решения нечего оценивать.'};const boardN=last.street==='FLOP'?3:last.street==='TURN'?4:last.street==='RIVER'?5:0;const spot={id:'USER_HAND',spotId:'USER_HAND',street:last.street,pos:`${h.heroSeat||'HERO'} vs ${h.villainSeat||'VILLAIN'}`,hero:h.hero||[],board:(h.board||[]).slice(0,boardN),stack:h.effStack||30,pot:last.potBefore||h.pot||0,ctx:last.action==='CALL'||last.action==='FOLD'||last.action==='RAISE'?`Facing bet ${last.pct||''}%`:'Checked to'};const r=gradeDecision(spot,last.action,last.pct??null);return{match:r.source==='NO_MODEL'?'NO_MODEL':r.source,confidence:r.confidence,result:r,summary:r.explanation}}
function stats(){return{...P.stats,totalPolicies:(P.stats.preflopPolicies||0)+(P.stats.postflopPolicies||0)+(P.stats.exactNodes||0)}}
window.PokerBrain={version:P.version,truth:P.truth,stats,gradeDecision,reviewLine,gradeRepair,conceptLabel,courseForConcept,analyzeHand,riverMath,nodeFor,classOf,boardArch,handBucket};
})();
