// task-context/library.js
// Библиотека тренировочных задач первого раздела: полный контекст раздачи.
// ~96 сценариев: префлоп (RFI/защита/3-бет/сквиз/пуш-фолд), постфлоп,
// турнирные стадии (баббл/ICM/ITM/PKO/финальный стол/анте), типы соперников.

import { emptyTask, OPPONENT_PROFILES } from './schema.js';
import { ADVANCED_TASKS } from './advancedTasks.js';
import { ADVANCED_TASKS_9B } from './advancedTasks9b.js';

let _seq = 0;
function T(o) {
  const d = emptyTask();
  const spot = Object.assign(d, o);
  if (typeof spot.opp === 'string') {
    const base = OPPONENT_PROFILES[spot.opp];
    spot.opp = base ? Object.assign({ name: spot.opp }, base) : { name: spot.opp, vpip: 21, pfr: 16, sample: 3400, style: 'ТАЙТ-АГРЕССИВНЫЙ', note: '' };
  }
  if (!spot.effStack && spot.heroStack) spot.effStack = Math.min(spot.heroStack, spot.villainStack || spot.heroStack);
  if (!spot.id) spot.id = 'LIB_' + (++_seq);
  return spot;
}

const H = (a) => a.split('').length === 1 ? a : a; // noop, keep authoring explicit

export const TASKS = [

  /* ============ ПРЕФЛОП · RFI (рейз первым) ============ */
  T({ id:'PRE_RFI_BTN_A8S', street:'ПРЕФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'54 LEFT', position:'BTN', hero:['A♠','8♠'], heroStack:30, villain:'BB', villainStack:28, opp:'РЕГ', board:[], pot:3.5, history:[{street:'ПРЕФЛОП', text:'До тебя все сфолдили, включая анте.', pot:3.5}], question:'Что делаешь с A8s на баттоне?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'RFI BTN', explain:'Баттон открывает широко. A8s сильна позицией, двумя оверкартами и реализацией equity — стандартный оупен.', difficulty:1, tags:['префлоп','RFI','позиция'] }),
  T({ id:'PRE_RFI_CO_KTS', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'8-MAX', left:'63 LEFT', position:'CO', hero:['K♣','T♣'], heroStack:36, villain:'BB', villainStack:33, opp:'РЕГ', board:[], pot:4.2, history:[{street:'ПРЕФЛОП', text:'УТГ и два игрока в середине сфолдили.', pot:4.2}], question:'Что делаешь с KTs в CO?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'RFI CO', explain:'CO открывает большинство suited Broadways. KTs играбельна и реализует equity в позиции.', difficulty:1, tags:['префлоп','RFI','позиция'] }),
  T({ id:'PRE_RFI_HJ_77', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'9-MAX', left:'71 LEFT', position:'HJ', hero:['7♣','7♥'], heroStack:41, villain:'BB', villainStack:39, opp:'РЕГ', board:[], pot:5.2, history:[{street:'ПРЕФЛОП', text:'Три игрока до тебя сфолдили.', pot:5.2}], question:'Что делаешь с 77 в HJ?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'RFI HJ', explain:'Средние пары из ранней позиции открываются на тонкую ценность. 77 достаточно для оупена в HJ.', difficulty:1, tags:['префлоп','RFI','пары'] }),
  T({ id:'PRE_RFI_UTG_AJO', street:'ПРЕФЛОП', format:'MTT', blinds:[1000,2000], ante:250, stage:'ПОЗДНЯЯ', table:'9-MAX', left:'29 LEFT', position:'UTG', hero:['A♦','J♦'], heroStack:52, villain:'BB', villainStack:49, opp:'РЕГ', board:[], pot:6.5, history:[{street:'ПРЕФЛОП', text:'Ты первый в раздаче.', pot:6.5}], question:'Что делаешь с AJo в UTG?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'RFI UTG', explain:'AJo — пограничный, но открываемый из UTG на глубоких стеках: сильные тузы реализуют equity.', difficulty:2, tags:['префлоп','RFI','ранняя позиция'] }),
  T({ id:'PRE_RFI_SB_22', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'12 LEFT', position:'SB', hero:['2♣','2♥'], heroStack:12, villain:'BB', villainStack:24, opp:'РЕГ', board:[], pot:4.4, history:[{street:'ПРЕФЛОП', text:'Все до тебя сфолдили, игра только против BB.', pot:4.4}], question:'Что делаешь с 22 в SB при 12 ББ?', options:['ФОЛД','ОЛЛ-ИН'], correct:'ОЛЛ-ИН', alsoOk:[], concept:'push-fold SB', explain:'При 12 ББ в SB средние/мелкие пары уже идут в пуш: фолд теряет анте и не реализует сет-ценность.', difficulty:2, tags:['префлоп','короткий стек','push-fold'] }),
  T({ id:'PRE_RFI_BTN_22_SHORT', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'БАББЛ', table:'6-MAX', left:'11 LEFT', position:'BTN', hero:['2♦','2♥'], heroStack:9, villain:'BB', villainStack:22, opp:'НИТ', board:[], pot:3.9, history:[{street:'ПРЕФЛОП', text:'До тебя все сфолдили. Баббл: 11 игроков, призовых 10.', pot:3.9}], question:'Что делаешь с 22 на батоне при 9 ББ на баббле?', options:['ФОЛД','ОЛЛ-ИН'], correct:'ОЛЛ-ИН', alsoOk:[], concept:'bubble push BTN', explain:'Против нитового BB и со стеком 9 ББ пуш 22 прибыльный: нит фолдит больше нормы, а сет/эксплойт достаточны.', difficulty:2, tags:['баббл','короткий стек','push-fold'] }),
  T({ id:'PRE_RFI_BTN_A5S_15', street:'ПРЕФЛОП', format:'MTT', blinds:[1000,2000], ante:250, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'24 LEFT', position:'BTN', hero:['A♠','5♠'], heroStack:15, villain:'BB', villainStack:26, opp:'РЕГ', board:[], pot:5.7, history:[{street:'ПРЕФЛОП', text:'Все до тебя сфолдили.', pot:5.7}], question:'Что делаешь с A5s на батоне при 15 ББ?', options:['ФОЛД','РЕЙЗ','ОЛЛ-ИН'], correct:'ОЛЛ-ИН', alsoOk:['РЕЙЗ'], concept:'push BTN 15BB', explain:'При 15 ББ A5s входит в прибыльный push-диапазон баттона, но рейз с последующим коллом тоже допустим.', difficulty:2, tags:['префлоп','короткий стек'] }),

  /* ============ ПРЕФЛОП · защита BB ============ */
  T({ id:'PRE_BB_K8S', street:'ПРЕФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'48 LEFT', position:'BB', hero:['K♦','8♦'], heroStack:40, villain:'BTN', villainStack:38, opp:'РЕГ', board:[], pot:5.2, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2 ББ, SB сфолдил.', pot:5.2}], question:'Что делаешь с K8s в BB против открытия BTN?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'КОЛЛ', alsoOk:['3-БЕТ'], concept:'BB defence', explain:'BB получает хорошую цену. K8s играбельна, но доминация против тайта выше — защита через колл, иногда 3-бет.', difficulty:1, tags:['префлоп','защита BB'] }),
  T({ id:'PRE_BB_76S', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'40 LEFT', position:'BB', hero:['7♣','6♣'], heroStack:44, villain:'BTN', villainStack:41, opp:'РЕГ', board:[], pot:6.0, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2 ББ, SB сфолдил.', pot:6.0}], question:'Что делаешь с 76s в BB?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'КОЛЛ', alsoOk:[], concept:'BB defence', explain:'Коннекторы в масти реализуют equity и хорошо ловят дровяные доски — классический колл из BB.', difficulty:1, tags:['префлоп','защита BB','коннекторы'] }),
  T({ id:'PRE_BB_T6O', street:'ПРЕФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'55 LEFT', position:'BB', hero:['T♦','6♠'], heroStack:42, villain:'BTN', villainStack:39, opp:'РЕГ', board:[], pot:5.2, history:[{street:'ПРЕФЛОП', text:'BTN открыл 3.5 ББ, SB сфолдил.', pot:5.2}], question:'Что делаешь с T6o в BB против крупного открытия?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'BB defence', explain:'T6o плохо реализует equity и часто доминируется. Против большого сайза защита не оправдана.', difficulty:2, tags:['префлоп','защита BB','офсают'] }),
  T({ id:'PRE_BB_A2S', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'35 LEFT', position:'BB', hero:['A♣','2♣'], heroStack:50, villain:'BTN', villainStack:47, opp:'РЕГ', board:[], pot:7.2, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2 ББ, SB сфолдил.', pot:7.2}], question:'Что делаешь с A2s в BB?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'КОЛЛ', alsoOk:['3-БЕТ'], concept:'BB defence', explain:'A2s — рука-кандидат в 3-бет-блеф, но и обычный колл хорош: масть и туз дают реализацию и флаш-потенциал.', difficulty:2, tags:['префлоп','защита BB'] }),
  T({ id:'PRE_BB_55_3X', street:'ПРЕФЛОП', format:'MTT', blinds:[1000,2000], ante:250, stage:'ПОЗДНЯЯ', table:'8-MAX', left:'27 LEFT', position:'BB', hero:['5♥','5♦'], heroStack:33, villain:'CO', villainStack:31, opp:'РЕГ', board:[], pot:8.0, history:[{street:'ПРЕФЛОП', text:'CO открыл 3 ББ, SB сфолдил.', pot:8.0}], question:'Что делаешь с 55 в BB против открытия CO?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'КОЛЛ', alsoOk:[], concept:'BB defence', explain:'Средняя пара из BB — защита через колл: сет-ценность против широкого диапазона CO.', difficulty:1, tags:['префлоп','защита BB','пары'] }),

  /* ============ ПРЕФЛОП · 3-бет и сквиз ============ */
  T({ id:'PRE_3B_SB_A5S', street:'ПРЕФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'58 LEFT', position:'SB', hero:['A♣','5♣'], heroStack:46, villain:'CO', villainStack:44, opp:'РЕГ', board:[], pot:5.0, history:[{street:'ПРЕФЛОП', text:'CO открыл 2.3 ББ, BTN сфолдил.', pot:5.0}], question:'Что делаешь с A5s в SB против открытия CO?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'3-БЕТ', alsoOk:[], concept:'polar 3-bet', explain:'A5s блокирует сильные Ax соперника и сохраняет equity после колла — классический 3-бет-блеф из SB.', difficulty:2, tags:['префлоп','3-бет','блеф'] }),
  T({ id:'PRE_3B_BB_KK', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'33 LEFT', position:'BB', hero:['K♥','K♦'], heroStack:60, villain:'BTN', villainStack:57, opp:'РЕГ', board:[], pot:6.8, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2 ББ, SB сфолдил.', pot:6.8}], question:'Что делаешь с KK в BB против открытия BTN?', options:['КОЛЛ','3-БЕТ'], correct:'3-БЕТ', alsoOk:[], concept:'3-bet value', explain:'KK — монстр; 3-бет собирает ценность и раздувает банк против широкого диапазона BTN.', difficulty:1, tags:['префлоп','3-бет','ценность'] }),
  T({ id:'PRE_3B_BTN_AQO', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'47 LEFT', position:'BTN', hero:['A♦','Q♠'], heroStack:70, villain:'BB', villainStack:66, opp:'РЕГ', board:[], pot:6.4, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2 ББ, BB 3-бетил 8 ББ.', pot:6.4}], question:'Что делаешь с AQo на BTN против 3-бета BB?', options:['ФОЛД','КОЛЛ','4-БЕТ'], correct:'КОЛЛ', alsoOk:['4-БЕТ'], concept:'flat vs 3-bet', explain:'AQo в позиции можно как коллить, так и 4-бетить. Колл сохраняет диапазон и реализует equity против сбалансированного BB.', difficulty:2, tags:['префлоп','vs 3-бет'] }),
  T({ id:'PRE_SQZ_AQS', street:'ПРЕФЛОП', format:'MTT', blinds:[1000,2000], ante:250, stage:'ПОЗДНЯЯ', table:'8-MAX', left:'26 LEFT', position:'SB', hero:['A♠','Q♠'], heroStack:65, villain:'BTN', villainStack:34, opp:'РЕГ', board:[], pot:12.5, history:[{street:'ПРЕФЛОП', text:'CO открыл 2.2 ББ, BTN заколлил.', pot:12.5}], question:'Что делаешь с AQs в SB при сквизе?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'3-БЕТ', alsoOk:[], concept:'squeeze', explain:'Сильный сквиз с AQs против двух оппонентов: блокирует тузы/дамы и часто забирает банк без шоудауна.', difficulty:2, tags:['префлоп','сквиз','3-бет'] }),
  T({ id:'PRE_VS3B_66', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'44 LEFT', position:'BB', hero:['6♣','6♦'], heroStack:52, villain:'BTN', villainStack:49, opp:'РЕГ', board:[], pot:9.0, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2, ты 3-бетил 8 ББ, BTN запушил 4-бет олл-ин на 49 ББ.', pot:9.0}], question:'Что делаешь с 66 против 4-бет-пуша?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'vs 4-bet', explain:'66 против 4-бет-пуша — дисперсный колл без сет-цены. Пара средняя, против сбалансированного пуша фолд.', difficulty:2, tags:['префлоп','vs 4-бет','пары'] }),

  /* ============ ФЛОП · с-бет / защита ============ */
  T({ id:'F_DRY_CBET', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'49 LEFT', position:'BTN', hero:['Q♣','J♣'], heroStack:38, villain:'BB', villainStack:36, opp:'РЕГ', board:['A♦','7♠','2♥'], pot:5.2, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BB чек.', pot:5.2}], question:'Что делаешь с QJs на сухом флопе A72?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'dry board c-bet', explain:'На сухом A-high маленький широкий с-бет хорошо работает: BB почти не попадает в пару/туз, fold equity высок.', difficulty:1, tags:['флоп','с-бет','сухая доска'] }),
  T({ id:'F_DYNAMIC_CBET', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'50 LEFT', position:'BTN', hero:['A♦','Q♣'], heroStack:42, villain:'BB', villainStack:40, opp:'РЕГ', board:['T♠','9♠','8♦'], pot:5.4, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BB чек.', pot:5.4}], question:'Что делаешь с AQ на динамичной доске T98?', options:['ЧЕК','СТАВКА'], correct:'ЧЕК', alsoOk:['СТАВКА'], concept:'dynamic board', explain:'T98 сильнее цепляет диапазон BB (стриты, дрова). Чек предпочтительнее автоматического range-bet — меньше убедительности.', difficulty:2, tags:['флоп','с-бет','динамичная доска'] }),
  T({ id:'F_OVERBET_VS', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'51 LEFT', position:'BB', hero:['7♣','6♣'], heroStack:40, villain:'BTN', villainStack:38, opp:'РЕГ', board:['K♠','7♦','2♥'], pot:5.4, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN ставит 125% банка.', pot:5.4}], question:'Что делаешь со слабой парой 76s против овербета?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'ФОЛД', alsoOk:[], concept:'vs overbet', explain:'Слабая пара резко теряет ценность против крупной полярной ставки — фолд, рука слишком низко в диапазоне продолжения.', difficulty:2, tags:['флоп','против овербета','пары'] }),
  T({ id:'F_SMALL_BET_DEF', street:'ФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'46 LEFT', position:'BB', hero:['9♠','8♠'], heroStack:50, villain:'BTN', villainStack:47, opp:'РЕГ', board:['Q♦','6♣','4♠'], pot:6.0, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BTN ставит 25% банка.', pot:6.0}], question:'Что делаешь с 98s против маленькой ставки?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'КОЛЛ', alsoOk:[], concept:'small bet defence', explain:'Против маленького размера BB обязан защищаться шире: 98s с двумя оверкартами и дровами — защита.', difficulty:2, tags:['флоп','защита','дрова'] }),
  T({ id:'F_3BET_POT_QQ', street:'ФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'30 LEFT', position:'BB', hero:['Q♥','Q♦'], heroStack:45, villain:'BTN', villainStack:42, opp:'РЕГ', board:['A♦','K♠','4♣'], pot:18, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB 3-бетил, BTN заколлил.', pot:18},{street:'ФЛОП', text:'BTN чек.', pot:18}], question:'Что делаешь с QQ в 3-бет-поте на AK4?', options:['ЧЕК','СТАВКА'], correct:'ЧЕК', alsoOk:[], concept:'3bet pot check', explain:'QQ имеет showdown, но на доске с тузом и королём ставка превращает руку в блеф — чек лучше.', difficulty:2, tags:['флоп','3-бет-пот','оверпара'] }),

  /* ============ ТЁРН · бареллинг / чек ============ */
  T({ id:'T_VALUE_BARREL', street:'ТЁРН', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'45 LEFT', position:'BTN', hero:['A♣','Q♣'], heroStack:34, villain:'BB', villainStack:32, opp:'РЕГ', board:['Q♦','8♠','3♣','2♥'], pot:8.8, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN ставит 33%, BB колл.', pot:8.8},{street:'ТЁРН', text:'BB чек.', pot:8.8}], question:'Что делаешь с топ-парой AQ на тёрне?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'turn value barrel', explain:'Сильная топ-пара на безопасном тёрне продолжает добирать: BB имеет много пар и дров.', difficulty:1, tags:['тёрн','бареллинг','ценность'] }),
  T({ id:'T_CHECK_SD', street:'ТЁРН', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'43 LEFT', position:'BTN', hero:['K♣','Q♦'], heroStack:40, villain:'BB', villainStack:38, opp:'РЕГ', board:['J♠','T♣','8♦','5♥'], pot:5.4, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'check-check.', pot:4.7},{street:'ТЁРН', text:'BB чек.', pot:5.4}], question:'Что делаешь с KQ на тёрне JT85?', options:['ЧЕК','СТАВКА'], correct:'ЧЕК', alsoOk:[], concept:'turn showdown', explain:'KQ имеет showdown и equity, но на JT85 раздувать банк не обязательно — чек контролирует размер.', difficulty:2, tags:['тёрн','чек','шоудаун'] }),
  T({ id:'T_POLAR_AK', street:'ТЁРН', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'28 LEFT', position:'CO', hero:['A♣','K♣'], heroStack:50, villain:'BB', villainStack:48, opp:'РЕГ', board:['9♣','7♣','2♦','K♥'], pot:14, history:[{street:'ПРЕФЛОП', text:'CO открыл, BB заколлил.', pot:5.6},{street:'ФЛОП', text:'CO ставит 40%, BB колл.', pot:14},{street:'ТЁРН', text:'BB чек.', pot:14}], question:'Что делаешь с AK + флаш-дро на тёрне?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'polar turn sizing', explain:'Топ-пара + нутовое флаш-дро — сильная полярная рука; крупная ставка раздувает банк и изолирует дрова.', difficulty:2, tags:['тёрн','поляризация','дрова'] }),

  /* ============ РИВЕР · тонкое значение / блеф-кетч ============ */
  T({ id:'R_THIN_VALUE', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'42 LEFT', position:'CO', hero:['K♥','Q♥'], heroStack:31, villain:'BB', villainStack:29, opp:'РЕГ', board:['K♣','9♦','5♠','2♥','2♣'], pot:18, history:[{street:'ПРЕФЛОП', text:'CO открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'CO 33%, BB колл.', pot:10},{street:'ТЁРН', text:'CO 66%, BB колл.', pot:18},{street:'РИВЕР', text:'BB чек.', pot:18}], question:'Что делаешь с KQ на ривере?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'thin value', explain:'Тонкое значение: худшие Kx и пары заплатят небольшой размер. Крупно ставить не нужно.', difficulty:2, tags:['ривер','тонкое значение'] }),
  T({ id:'R_BLUFFCATCH', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'41 LEFT', position:'BB', hero:['K♠','J♦'], heroStack:26, villain:'BTN', villainStack:24, opp:'РЕГ', board:['K♥','9♣','4♦','7♠','A♣'], pot:20, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 75%, BB колл.', pot:11},{street:'ТЁРН', text:'BTN 75%, BB колл.', pot:20},{street:'РИВЕР', text:'BTN ставит 140%.', pot:20}], question:'Что делаешь с KJ против овербета на ривере?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'river bluffcatch', explain:'Сначала required equity, затем value/bluff и блокеры. Топ-пара с KJ слишком низко против полярного овербета — фолд.', difficulty:2, tags:['ривер','блеф-кетч','овербет'] }),
  T({ id:'R_PRICE_DEF', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'39 LEFT', position:'BB', hero:['Q♠','9♣'], heroStack:32, villain:'BTN', villainStack:30, opp:'РЕГ', board:['Q♥','8♦','4♣','3♠','2♦'], pot:24, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'check-check.', pot:4.7},{street:'ТЁРН', text:'BB ставит 50%, BTN колл.', pot:11},{street:'РИВЕР', text:'BTN ставит 25%.', pot:24}], question:'Что делаешь с Q9 против маленькой ставки на ривере?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'КОЛЛ', alsoOk:[], concept:'price defence', explain:'Маленький river-size даёт отличную цену: топ-пара Q9 при required equity легко коллится.', difficulty:2, tags:['ривер','защита','цена'] }),
  T({ id:'R_BIG_VALUE', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'40 LEFT', position:'BTN', hero:['A♣','5♣'], heroStack:35, villain:'BB', villainStack:33, opp:'РЕГ', board:['A♦','A♠','7♥','4♣','2♦'], pot:19, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 33%, BB колл.', pot:9},{street:'ТЁРН', text:'BTN 33%, BB колл.', pot:14},{street:'РИВЕР', text:'BB чек.', pot:19}], question:'Что делаешь с трипсом A5s на ривере?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'river value', explain:'Трипс сохраняет сильный value target; размер должен добирать с более слабых Ax.', difficulty:1, tags:['ривер','ценность','трипс'] }),

  /* ============ ТУРНИР · баббл / ICM / PKO / финальный стол ============ */
  T({ id:'TOUR_BUBBLE_A7O', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'БАББЛ', table:'6-MAX', left:'8 LEFT', position:'BTN', hero:['A♦','7♠'], heroStack:18, villain:'BB', villainStack:20, opp:'НИТ', board:[], pot:4.0, history:[{street:'ПРЕФЛОП', text:'Баббл: 8 игроков, призовых 7. До тебя все сфолдили.', pot:4.0}], question:'Что делаешь с A7o на баббле против нитового BB?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'bubble steal', explain:'На баббле нитовый BB фолдит слишком часто. Оупен с A7o в позиции — прибыльный стил.', difficulty:2, tags:['баббл','стил','ICM'] }),
  T({ id:'TOUR_BUBBLE_77_CALL', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'БАББЛ', table:'6-MAX', left:'9 LEFT', position:'BB', hero:['7♥','7♦'], heroStack:22, villain:'SB', villainStack:24, opp:'РЕГ', board:[], pot:5.6, history:[{street:'ПРЕФЛОП', text:'Баббл. SB запушил олл-ин на 24 ББ.', pot:5.6}], question:'Что делаешь с 77 в BB против пуша на баббле?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'bubble ICM fold', explain:'На баббле 77 против пуша из SB — пограничный ICM-фолд: лишняя дисперсия дороже рейза на стек.', difficulty:3, tags:['баббл','ICM','фолд'] }),
  T({ id:'TOUR_ITM_AQS', street:'ПРЕФЛОП', format:'MTT', blinds:[1000,2000], ante:250, stage:'ITM', table:'6-MAX', left:'22 LEFT', position:'CO', hero:['A♠','Q♠'], heroStack:25, villain:'BB', villainStack:23, opp:'РЕГ', board:[], pot:6.7, history:[{street:'ПРЕФЛОП', text:'ITM. CO открывает олл-ин на 25 ББ.', pot:6.7}], question:'Что делаешь с AQs в ITM при 25 ББ?', options:['РЕЙЗ','ОЛЛ-ИН'], correct:'ОЛЛ-ИН', alsoOk:['РЕЙЗ'], concept:'ITM push', explain:'AQs в ITM на 25 ББ — шов: сильная рука, короткий стек, раздувать 4-бет нет смысла.', difficulty:2, tags:['ITM','короткий стек','пуш'] }),
  T({ id:'TOUR_PKO_BOUNTY', street:'ПРЕФЛОП', format:'PKO', blinds:[800,1600], ante:200, stage:'ITM', table:'6-MAX', left:'18 LEFT', position:'BB', hero:['A♦','J♥'], heroStack:30, villain:'BTN', villainStack:31, opp:'РЕГ', board:[], pot:7.2, history:[{street:'ПРЕФЛОП', text:'PKO. BTN с баунти запушил олл-ин на 31 ББ. У тебя накрывающий баунти.', pot:7.2}], question:'Что делаешь с AJo против пуша с баунти?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'PKO call', explain:'В PKO баунти добавляет overlay. AJo против широкого баунти-пуша BTN — прибыльный колл с накрытием.', difficulty:2, tags:['PKO','баунти','колл'] }),
  T({ id:'TOUR_FT_QQ', street:'ПРЕФЛОП', format:'MTT', blinds:[1200,2400], ante:300, stage:'ФИНАЛЬНЫЙ СТОЛ', table:'9-MAX', left:'7 LEFT', position:'CO', hero:['Q♦','Q♥'], heroStack:28, villain:'BB', villainStack:45, opp:'РЕГ', board:[], pot:8.1, history:[{street:'ПРЕФЛОП', text:'Финальный стол, 7 left. CO открывает, BB запушил олл-ин на 45 ББ.', pot:8.1}], question:'Что делаешь с QQ против пуша чиплидера на финальном столе?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'final table ICM', explain:'QQ против пуша — колл даже с учётом ICM: слишком много рук, с которыми доминация на нашей стороне.', difficulty:2, tags:['финальный стол','ICM','колл'] }),
  T({ id:'TOUR_ANTE_3X', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:400, stage:'ПОЗДНЯЯ', table:'9-MAX', left:'20 LEFT', position:'BB', hero:['T♣','9♣'], heroStack:34, villain:'BTN', villainStack:32, opp:'РЕГ', board:[], pot:6.6, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.2 ББ, SB сфолдил. Анте высокие (400).', pot:6.6}], question:'Что делаешь с T9s в BB против высокого анте?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'ante defence', explain:'Высокое анте раздувает банк и снижает эффективный стек — BB обязан защищаться шире, T9s коллится.', difficulty:2, tags:['анте','защита BB','поздняя стадия'] }),

  /* ============ ТИПЫ СОПЕРНИКОВ · эксплойт ============ */
  T({ id:'OPP_NIT_FOLD', street:'РИВЕР', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'38 LEFT', position:'BB', hero:['Q♠','J♠'], heroStack:34, villain:'BTN', villainStack:32, opp:'НИТ', board:['A♣','K♦','7♠','4♠','3♦'], pot:22, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'check-check.', pot:5.2},{street:'ТЁРН', text:'BB ставит 50%, BTN колл.', pot:12},{street:'РИВЕР', text:'BTN ставит 80%.', pot:22}], question:'Что делаешь с QJ против нитового овербета?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'exploit nit', explain:'Нит почти не блефует на ривере: его овербет — почти всегда ценность. QJ слишком низко — фолд.', difficulty:2, tags:['соперник','нит','ривер'] }),
  T({ id:'OPP_STATION_VALUE', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'36 LEFT', position:'BTN', hero:['K♠','Q♠'], heroStack:38, villain:'BB', villainStack:36, opp:'СТЕЦИОНЕР', board:['K♦','9♣','5♠','2♥','2♣'], pot:17, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:10},{street:'ТЁРН', text:'BTN 60%, BB колл.', pot:17},{street:'РИВЕР', text:'BB чек.', pot:17}], question:'Что делаешь с KQ против стационарного BB?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'exploit station', explain:'Стационер коллит слишком широко — тонкое значение против него превращается в обычное. Ставь крупно.', difficulty:2, tags:['соперник','стационер','ривер'] }),
  T({ id:'OPP_MANIAC_CATCH', street:'РИВЕР', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'31 LEFT', position:'BB', hero:['T♥','9♥'], heroStack:36, villain:'BTN', villainStack:33, opp:'МАНИАК', board:['9♣','7♦','4♠','2♣','6♠'], pot:24, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.6},{street:'ФЛОП', text:'BB чек, BTN 70%, BB колл.', pot:12},{street:'ТЁРН', text:'BB чек, BTN 90%, BB колл.', pot:24},{street:'РИВЕР', text:'BTN ставит 100%.', pot:24}], question:'Что делаешь с топ-парой против маниака?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'exploit maniac', explain:'Маниак ставит на каждой улице с мусором — топ-пара T9 отличный блеф-кетч. Фолдить нельзя.', difficulty:2, tags:['соперник','маниак','блеф-кетч'] }),
  T({ id:'OPP_AGRO_3B', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'34 LEFT', position:'BTN', hero:['J♥','J♦'], heroStack:55, villain:'BB', villainStack:52, opp:'АГРО-РЕГ', board:[], pot:5.8, history:[{street:'ПРЕФЛОП', text:'BB 3-бетил 9 ББ против твоего оупена.', pot:5.8}], question:'Что делаешь с JJ против 3-бета агрессивного рега?', options:['КОЛЛ','4-БЕТ'], correct:'КОЛЛ', alsoOk:['4-БЕТ'], concept:'vs agro 3-bet', explain:'Против агрессивного BB, который часто 3-бетил, JJ коллится в позиции, сохраняя диапазон на блефы.', difficulty:2, tags:['соперник','агрессивный рег','JJ'] }),
  T({ id:'OPP_LOVER_CBET', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'37 LEFT', position:'BB', hero:['9♣','8♣'], heroStack:44, villain:'BTN', villainStack:42, opp:'ЛЮБИТЕЛЬ', board:['Q♦','6♣','4♠'], pot:5.0, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN ставит 75%.', pot:5.0}], question:'Что делаешь с 98s против большого с-бета любителя?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'ФОЛД', alsoOk:[], concept:'exploit lover', explain:'Любитель ставит с-бет почти только с парой/тузом — защита через 98s слишком широка, фолд.', difficulty:2, tags:['соперник','любитель','флоп'] }),

  /* ============ КОРОТКИЙ СТЕК · пуш-фолд / анте ============ */
  T({ id:'SHORT_BTN_A9O', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'15 LEFT', position:'BTN', hero:['A♦','9♠'], heroStack:8, villain:'BB', villainStack:20, opp:'РЕГ', board:[], pot:4.4, history:[{street:'ПРЕФЛОП', text:'Все до тебя сфолдили.', pot:4.4}], question:'Что делаешь с A9o на батоне при 8 ББ?', options:['ФОЛД','ОЛЛ-ИН'], correct:'ОЛЛ-ИН', alsoOk:[], concept:'push-fold BTN', explain:'A9o при 8 ББ — стандартный пуш: сильная рука для открытия шов-диапазона баттона.', difficulty:1, tags:['короткий стек','push-fold'] }),
  T({ id:'SHORT_BB_87S', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'16 LEFT', position:'BB', hero:['8♦','7♦'], heroStack:6, villain:'BTN', villainStack:9, opp:'РЕГ', board:[], pot:3.9, history:[{street:'ПРЕФЛОП', text:'BTN запушил олл-ин на 9 ББ.', pot:3.9}], question:'Что делаешь с 87s в BB при 6 ББ против пуша?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'short stack call', explain:'87s при 6 ББ против пуша широкого BTN — колл: рука имеет хороший потенциал при пот-оддсах.', difficulty:2, tags:['короткий стек','колл'] }),
  T({ id:'SHORT_SB_55', street:'ПРЕФЛОП', format:'MTT', blinds:[1000,2000], ante:250, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'13 LEFT', position:'SB', hero:['5♥','5♣'], heroStack:10, villain:'BB', villainStack:23, opp:'РЕГ', board:[], pot:5.7, history:[{street:'ПРЕФЛОП', text:'Все до тебя сфолдили.', pot:5.7}], question:'Что делаешь с 55 в SB при 10 ББ?', options:['ФОЛД','ОЛЛ-ИН'], correct:'ОЛЛ-ИН', alsoOk:[], concept:'push-fold SB', explain:'55 в SB при 10 ББ идёт в пуш: средние пары держат equity против колл-диапазона BB.', difficulty:2, tags:['короткий стек','push-fold','пары'] }),
  T({ id:'SHORT_BB_A5O', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'14 LEFT', position:'BB', hero:['A♠','5♦'], heroStack:7, villain:'BTN', villainStack:11, opp:'РЕГ', board:[], pot:4.6, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.5 ББ, SB сфолдил.', pot:4.6}], question:'Что делаешь с A5o в BB при 7 ББ?', options:['ФОЛД','ОЛЛ-ИН','КОЛЛ'], correct:'ОЛЛ-ИН', alsoOk:['КОЛЛ'], concept:'short stack defend', explain:'При 7 ББ A5o в BB — пуш против оупена: лучше изолировать, чем защищаться коллом с низкой реализацией.', difficulty:2, tags:['короткий стек','push-fold','A5o'] }),

  /* ============ РАЗНОЕ · блефы, диапазоны, линии ============ */
  T({ id:'MISC_RIVER_BLUF', street:'РИВЕР', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'26 LEFT', position:'BTN', hero:['6♠','5♠'], heroStack:44, villain:'BB', villainStack:41, opp:'РЕГ', board:['Q♦','9♣','5♥','3♠','2♦'], pot:24, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.6},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:12},{street:'ТЁРН', text:'BTN 66%, BB колл.', pot:24},{street:'РИВЕР', text:'BB чек.', pot:24}], question:'Что делаешь с 65s после трёх улиц агрессии?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'river bluff', explain:'Проигрышная рука с блокерами на стрит — хороший блеф на ривере: ставка забирает банк, когда BB имеет много пар без топ-силы.', difficulty:3, tags:['ривер','блеф','блокеры'] }),
  T({ id:'MISC_FLOATPFLOP', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'47 LEFT', position:'BB', hero:['A♦','5♦'], heroStack:52, villain:'BTN', villainStack:49, opp:'РЕГ', board:['J♣','7♠','4♦'], pot:5.0, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN ставит 33%.', pot:5.0}], question:'Что делаешь с A5s бэкдор-флаш-дро на флопе?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'КОЛЛ', alsoOk:['РЕЙЗ'], concept:'float with backdoor', explain:'A5s с бэкдором и оверкартой — кандидат на флоат: колл в позиции OOP, иногда рейз-блеф.', difficulty:2, tags:['флоп','флоат','бэкдор'] }),
  T({ id:'MISC_XR_TPTK', street:'ТЁРН', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'29 LEFT', position:'BB', hero:['A♥','Q♠'], heroStack:46, villain:'BTN', villainStack:43, opp:'АГРО-РЕГ', board:['A♦','9♣','5♠','2♥'], pot:11, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.6},{street:'ФЛОП', text:'BB чек, BTN 70%, BB колл.', pot:11},{street:'ТЁРН', text:'BTN ставит 66%.', pot:11}], question:'Что делаешь с топ-парой против агрессора на тёрне?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:['КОЛЛ'], concept:'turn check-raise', explain:'AQ на A952 — сильная рука, против агрессивного рега чек-рейз на тёрне собирает ценность и изолирует.', difficulty:3, tags:['тёрн','чек-рейз','ценность'] }),
  T({ id:'MISC_CLEAN_LINE', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'43 LEFT', position:'BTN', hero:['A♠','K♠'], heroStack:39, villain:'BB', villainStack:37, opp:'РЕГ', board:['K♦','9♣','5♠','3♥','8♠'], pot:16, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 33%, BB колл.', pot:9},{street:'ТЁРН', text:'BTN 66%, BB колл.', pot:16},{street:'РИВЕР', text:'BB чек.', pot:16}], question:'Что делаешь с AK после трёх улиц?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'clean line value', explain:'AK на сухой доске держит топ-пару до ривера — продолжай добирать, линия логична.', difficulty:1, tags:['ривер','ценность','чистая линия'] }),
  T({ id:'MISC_DONK_OVERPAIR', street:'ФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'35 LEFT', position:'BB', hero:['J♥','J♠'], heroStack:48, villain:'BTN', villainStack:45, opp:'РЕГ', board:['Q♣','8♦','3♠'], pot:5.6, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BB чек, BTN ставит 33%.', pot:5.6}], question:'Что делаешь с JJ против с-бета на Q83?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'КОЛЛ', alsoOk:[], concept:'overpair vs c-bet', explain:'JJ — оверпара выше 8, ниже дамы. Колл держит диапазон; рейз раздувает банк с уязвимой рукой.', difficulty:2, tags:['флоп','оверпара','защита'] }),

  /* ============ ПРЕФЛОП · кэш, глубокие стеки, ранние позиции ============ */
  T({ id:'CASH_100BB_AA', street:'ПРЕФЛОП', format:'CASH', blinds:[5,10], ante:0, stage:'СРЕДНЯЯ', table:'6-MAX', left:'6 СТЕКОВ', position:'BTN', hero:['A♠','A♥'], heroStack:100, villain:'BB', villainStack:97, opp:'РЕГ', board:[], pot:6.4, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.5 ББ, BB 3-бетил 9 ББ.', pot:6.4}], question:'Что делаешь с AA против 3-бета на 100 ББ?', options:['КОЛЛ','4-БЕТ'], correct:'4-БЕТ', alsoOk:[], concept:'4-bet value', explain:'AA на глубоких кэш-стеках — 4-бет по ценности: 4-бет раздувает банк, иногда с ре-пушем от соперника.', difficulty:1, tags:['кэш','AA','4-бет'] }),
  T({ id:'CASH_100BB_SETMINING', street:'ПРЕФЛОП', format:'CASH', blinds:[5,10], ante:0, stage:'СРЕДНЯЯ', table:'6-MAX', left:'6 СТЕКОВ', position:'BB', hero:['4♣','4♦'], heroStack:100, villain:'CO', villainStack:200, opp:'ЛЮБИТЕЛЬ', board:[], pot:1.5, history:[{street:'ПРЕФЛОП', text:'CO открыл 3 ББ, ты в BB.', pot:1.5}], question:'Что делаешь с 44 в BB против глубокого стека?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'set-mining', explain:'Сет-майнинг на 100 ББ с эффективным 200: выплата на сет 12+ раз окупает колл.', difficulty:1, tags:['кэш','сет-майнинг','пары'] }),
  T({ id:'CASH_MP_KQS', street:'ПРЕФЛОП', format:'CASH', blinds:[10,20], ante:0, stage:'СРЕДНЯЯ', table:'9-MAX', left:'9 СТЕКОВ', position:'MP', hero:['K♠','Q♠'], heroStack:120, villain:'BB', villainStack:118, opp:'РЕГ', board:[], pot:1.5, history:[{street:'ПРЕФЛОП', text:'UTG сфолдил, до тебя нет открытий.', pot:1.5}], question:'Что делаешь с KQs в MP?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'RFI MP', explain:'KQs — стандартный оупен из MP на кэш-столах: сильная масть, хорошая реализация.', difficulty:1, tags:['кэш','RFI','KQs'] }),
  T({ id:'PRE_ISO_LIMP', street:'ПРЕФЛОП', format:'CASH', blinds:[5,10], ante:0, stage:'СРЕДНЯЯ', table:'9-MAX', left:'9 СТЕКОВ', position:'BTN', hero:['A♠','J♦'], heroStack:100, villain:'MP', villainStack:85, opp:'ЛЮБИТЕЛЬ', board:[], pot:2.0, history:[{street:'ПРЕФЛОП', text:'MP залимповал 1 ББ, двое коллируют.', pot:2.0}], question:'Что делаешь с AJo после лимпа?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'iso-raise', explain:'Изоляция лимпов с AJo на баттоне — ставка 4-5 ББ: изолируем слабых лимперов, позиция даёт реализацию.', difficulty:2, tags:['кэш','изоляция','лимп'] }),
  T({ id:'PRE_3B_JJ_AGAINST', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'45 LEFT', position:'CO', hero:['J♦','J♥'], heroStack:68, villain:'BTN', villainStack:64, opp:'РЕГ', board:[], pot:5.4, history:[{street:'ПРЕФЛОП', text:'CO открыл 2.2, BTN 3-бетил 9 ББ.', pot:5.4}], question:'Что делаешь с JJ против 3-бета на баттоне?', options:['ФОЛД','КОЛЛ','4-БЕТ'], correct:'КОЛЛ', alsoOk:['4-БЕТ'], concept:'flat vs 3-bet', explain:'JJ против 3-бета из позиции — колл или редкий 4-бет. Колл сохраняет диапазон и сет-ценность.', difficulty:2, tags:['префлоп','JJ','vs 3-бет'] }),
  T({ id:'PRE_4BET_BLUF_A5S', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'32 LEFT', position:'BTN', hero:['A♣','5♣'], heroStack:70, villain:'BB', villainStack:67, opp:'АГРО-РЕГ', board:[], pot:6.4, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB 3-бетил 10 ББ.', pot:6.4}], question:'Что делаешь с A5s против агрессивного 3-бета?', options:['ФОЛД','КОЛЛ','4-БЕТ'], correct:'4-БЕТ', alsoOk:[], concept:'4-bet bluff', explain:'A5s блокирует AA/AK/KK — классический 4-бет-блеф против агрессивного BB, который 3-бетит широко.', difficulty:3, tags:['префлоп','4-бет','блеф'] }),

  /* ============ ФЛОП · больше сценариев ============ */
  T({ id:'F_TPTK_DRY', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'46 LEFT', position:'BTN', hero:['A♠','Q♠'], heroStack:40, villain:'BB', villainStack:38, opp:'РЕГ', board:['A♦','7♣','2♠'], pot:5.2, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BB чек.', pot:5.2}], question:'Что делаешь с топ-парой AQ на сухом флопе?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'c-bet TPTK', explain:'Топ-пара + топ-кикер на сухой доске — чек-бек теряет ценность. Маленький широкий с-бет.', difficulty:1, tags:['флоп','с-бет','топ-пара'] }),
  T({ id:'F_MONOTONE', street:'ФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'41 LEFT', position:'BB', hero:['K♥','9♥'], heroStack:36, villain:'BTN', villainStack:34, opp:'РЕГ', board:['8♥','5♥','2♥'], pot:5.2, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BTN ставит 50%.', pot:5.2}], question:'Что делаешь с флаш-дро на моноборде?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'КОЛЛ', alsoOk:[], concept:'monotone defence', explain:'Флаш-дро на моноборде имеет ценность, но рейз теряет смысл — BB коллит и реализует флаш.', difficulty:2, tags:['флоп','флаш-дро','моноборд'] }),
  T({ id:'F_PAIRED_OVERBET', street:'ФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'30 LEFT', position:'BB', hero:['Q♥','Q♣'], heroStack:44, villain:'BTN', villainStack:41, opp:'РЕГ', board:['K♦','K♣','5♠'], pot:5.6, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BTN ставит 100% банка.', pot:5.6}], question:'Что делаешь с QQ на спаренных королях против овербета?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'КОЛЛ', alsoOk:[], concept:'paired board defence', explain:'QQ на KK5 против овербета — топ-пара ниже старшей пары. Против полярной ставки защищаемся коллом с блокерами.', difficulty:3, tags:['флоп','спаренная доска','защита'] }),
  T({ id:'F_GUTSHOT_RAISE', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'44 LEFT', position:'BB', hero:['9♥','8♠'], heroStack:48, villain:'BTN', villainStack:46, opp:'РЕГ', board:['J♣','T♠','2♥'], pot:5.0, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN ставит 33%.', pot:5.0}], question:'Что делаешь с гатшотом + оверкартами против с-бета?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:['КОЛЛ'], concept:'semi-bluff raise', explain:'98 на JT2 с гатшотом и бэкдором — кандидат на чек-рейз-блеф: много дров, мало шоудауна.', difficulty:3, tags:['флоп','полублеф','гатшот'] }),

  /* ============ ТЁРН · больше сценариев ============ */
  T({ id:'T_OVERBET_2', street:'ТЁРН', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'40 LEFT', position:'BB', hero:['9♣','9♠'], heroStack:42, villain:'BTN', villainStack:40, opp:'РЕГ', board:['A♦','9♥','4♠','2♣'], pot:12, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BB чек, BTN 40%, BB колл.', pot:12},{street:'ТЁРН', text:'BTN ставит 110% банка.', pot:12}], question:'Что делаешь с сетом против овербета на тёрне?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:['КОЛЛ'], concept:'set vs overbet', explain:'Сет на тёрне — монстр. Против полярного овербета чек-рейз добирает и изолирует. Колл тоже приемлем.', difficulty:2, tags:['тёрн','сет','овербет'] }),
  T({ id:'T_PROTECTION', street:'ТЁРН', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'43 LEFT', position:'BTN', hero:['K♠','K♦'], heroStack:38, villain:'BB', villainStack:36, opp:'РЕГ', board:['J♣','7♠','5♥','9♦'], pot:10, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 33%, BB колл.', pot:10},{street:'ТЁРН', text:'BB чек.', pot:10}], question:'Что делаешь с KK на тёрне J759?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'turn protection', explain:'KK — оверпара, но на J759 есть дрова (T8, 86). Ставка на тёрне собирает ценность и защищает.', difficulty:1, tags:['тёрн','защита','оверпара'] }),
  T({ id:'T_BACKDOOR_TRAP', street:'ТЁРН', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'27 LEFT', position:'BTN', hero:['A♦','A♠'], heroStack:46, villain:'BB', villainStack:43, opp:'РЕГ', board:['8♣','5♦','2♥','Q♠'], pot:13, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.6},{street:'ФЛОП', text:'BTN 50%, BB колл.', pot:13},{street:'ТЁРН', text:'BB чек.', pot:13}], question:'Что делаешь с AA на безопасном тёрне?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'turn value', explain:'AA на Q852 — топ-оверпара. Ставка на тёрне добирает с пар и дров; BB редко имеет руку сильнее.', difficulty:1, tags:['тёрн','ценность','AA'] }),

  /* ============ РИВЕР · больше сценариев ============ */
  T({ id:'R_CHECK_BEHIND', street:'РИВЕР', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'42 LEFT', position:'BTN', hero:['A♦','9♠'], heroStack:37, villain:'BB', villainStack:35, opp:'РЕГ', board:['A♣','K♦','7♠','4♥','2♣'], pot:16, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:12},{street:'ТЁРН', text:'BTN 50%, BB колл.', pot:16},{street:'РИВЕР', text:'BB чек.', pot:16}], question:'Что делаешь с A9 на ривере AK742?', options:['ЧЕК','СТАВКА'], correct:'ЧЕК', alsoOk:[], concept:'river check behind', explain:'A9 с топ-парой и слабым кикером: ставка на ривере рискует получить рейз, а худшие руки мало платят. Чек-бек.', difficulty:2, tags:['ривер','чек-бек','тонко'] }),
  T({ id:'R_OVERBET_FOLD', street:'РИВЕР', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'29 LEFT', position:'BB', hero:['J♥','T♣'], heroStack:30, villain:'BTN', villainStack:28, opp:'РЕГ', board:['Q♦','9♣','6♠','4♥','3♠'], pot:24, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.6},{street:'ФЛОП', text:'check-check.', pot:5.6},{street:'ТЁРН', text:'BB ставит 60%, BTN колл.', pot:13},{street:'РИВЕР', text:'BTN ставит 130% банка.', pot:24}], question:'Что делаешь с парой на ривере против овербета?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'overbet fold', explain:'Пара JT слишком низко против полярного овербета на ривере: фолд без блокаторов и без read на блеф.', difficulty:2, tags:['ривер','овербет','фолд'] }),
  T({ id:'R_KEVALUATE', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'39 LEFT', position:'CO', hero:['A♣','Q♥'], heroStack:36, villain:'BB', villainStack:34, opp:'РЕГ', board:['K♦','9♠','5♥','2♣','7♦'], pot:20, history:[{street:'ПРЕФЛОП', text:'CO открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'CO 40%, BB колл.', pot:12},{street:'ТЁРН', text:'CO 60%, BB колл.', pot:20},{street:'РИВЕР', text:'BB чек.', pot:20}], question:'Что делаешь с AQ (промах) на ривере?', options:['ЧЕК','СТАВКА'], correct:'ЧЕК', alsoOk:[], concept:'give up river', explain:'AQ без пары — лучшая ставка-блеф имеет худшие блокеры. Против сбалансированного BB чек-бек: рука почти всегда бита.', difficulty:2, tags:['ривер','сдаться','блеф'] }),

  /* ============ ТУРНИР · ICM / PKO / финальный стол ============ */
  T({ id:'TOUR_ICM_88', street:'ПРЕФЛОП', format:'MTT', blinds:[1200,2400], ante:300, stage:'БАББЛ', table:'6-MAX', left:'9 LEFT', position:'BB', hero:['8♥','8♣'], heroStack:20, villain:'SB', villainStack:21, opp:'РЕГ', board:[], pot:7.8, history:[{street:'ПРЕФЛОП', text:'Баббл: 9 left, призовых 8. SB запушил 21 ББ.', pot:7.8}], question:'Что делаешь с 88 на баббле против пуша?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'bubble ICM', explain:'На баббле 88 против пуша — ICM-фолд: приз за 9-е место стоит больше, чем дисперсия вылета.', difficulty:3, tags:['баббл','ICM','фолд'] }),
  T({ id:'TOUR_PKO_77', street:'ПРЕФЛОП', format:'PKO', blinds:[1000,2000], ante:250, stage:'ITM', table:'6-MAX', left:'15 LEFT', position:'BTN', hero:['7♥','7♣'], heroStack:22, villain:'BB', villainStack:23, opp:'РЕГ', board:[], pot:6.7, history:[{street:'ПРЕФЛОП', text:'PKO, ITM. BTN открывает, BB с баунти запушил 23 ББ.', pot:6.7}], question:'Что делаешь с 77 против баунти-пуша?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'PKO call 77', explain:'Баунти даёт overlay. 77 против широкого баунти-пуша BB — колл, если покрываем.', difficulty:2, tags:['PKO','баунти','пары'] }),
  T({ id:'TOUR_FT_AK', street:'ПРЕФЛОП', format:'MTT', blinds:[1500,3000], ante:400, stage:'ФИНАЛЬНЫЙ СТОЛ', table:'9-MAX', left:'5 LEFT', position:'SB', hero:['A♠','K♦'], heroStack:26, villain:'BB', villainStack:40, opp:'РЕГ', board:[], pot:2.7, history:[{street:'ПРЕФЛОП', text:'Финальный стол, 5 left. Все до SB сфолдили.', pot:2.7}], question:'Что делаешь с AK в SB против чиплидера?', options:['ОЛЛ-ИН','РЕЙЗ'], correct:'ОЛЛ-ИН', alsoOk:['РЕЙЗ'], concept:'final table AK', explain:'AK при 26 ББ — шов из SB: доминируем большинство рук, раздувать рейз-фолд нет смысла.', difficulty:2, tags:['финальный стол','AK','пуш'] }),
  T({ id:'TOUR_ITM_FOLD_AJO', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'ITM', table:'6-MAX', left:'20 LEFT', position:'CO', hero:['A♠','J♦'], heroStack:24, villain:'BTN', villainStack:26, opp:'РЕГ', board:[], pot:5.6, history:[{street:'ПРЕФЛОП', text:'ITM, 20 left. CO открывает 2.2, BTN 3-бетил олл-ин на 26 ББ.', pot:5.6}], question:'Что делаешь с AJo против 3-бет-пуша в ITM?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'ITM fold AJo', explain:'AJo против 3-бет-пуша в ITM — фолд: доминируется Ax и парами, дисперсия не окупается при ICM.', difficulty:2, tags:['ITM','ICM','фолд'] }),
  T({ id:'TOUR_BUBBLE_STEAL', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'БАББЛ', table:'8-MAX', left:'10 LEFT', position:'CO', hero:['9♦','8♦'], heroStack:25, villain:'BB', villainStack:28, opp:'НИТ', board:[], pot:4.2, history:[{street:'ПРЕФЛОП', text:'Баббл, 10 left. До тебя все сфолдили.', pot:4.2}], question:'Что делаешь с 98s на баббле в CO?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'bubble open', explain:'На баббле оппоненты фолдят больше нормы — 98s открывается шире, чем обычно.', difficulty:2, tags:['баббл','стил','коннекторы'] }),
  T({ id:'TOUR_PKO_DEFEND', street:'ПРЕФЛОП', format:'PKO', blinds:[800,1600], ante:200, stage:'ITM', table:'6-MAX', left:'16 LEFT', position:'BB', hero:['9♣','7♣'], heroStack:18, villain:'BTN', villainStack:20, opp:'РЕГ', board:[], pot:5.8, history:[{street:'ПРЕФЛОП', text:'PKO. BTN открыл 2.2, SB сфолдил.', pot:5.8}], question:'Что делаешь с 97s в BB против оупена в PKO?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'PKO defend', explain:'В PKO оппоненты шире защищаются и реже фолдят; 97s в BB защищается коллом против оупена BTN.', difficulty:2, tags:['PKO','защита BB','коннекторы'] }),

  /* ============ ТИПЫ СОПЕРНИКОВ · эксплойт 2 ============ */
  T({ id:'OPP_NIT_3B', street:'ПРЕФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'44 LEFT', position:'BTN', hero:['K♦','Q♦'], heroStack:58, villain:'BB', villainStack:55, opp:'НИТ', board:[], pot:5.2, history:[{street:'ПРЕФЛОП', text:'BB 3-бетил 10 ББ против твоего оупена.', pot:5.2}], question:'Что делаешь с KQs против 3-бета нита?', options:['ФОЛД','КОЛЛ','4-БЕТ'], correct:'ФОЛД', alsoOk:[], concept:'exploit nit 3b', explain:'Нит 3-бетит почти только AA/KK/AK. KQs против такой плотности — фолд, дисперсия не окупается.', difficulty:2, tags:['соперник','нит','vs 3-бет'] }),
  T({ id:'OPP_STATION_BARREL', street:'ТЁРН', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'37 LEFT', position:'BTN', hero:['A♥','J♣'], heroStack:42, villain:'BB', villainStack:39, opp:'СТЕЦИОНЕР', board:['A♦','9♣','5♠','2♥'], pot:12, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:12},{street:'ТЁРН', text:'BB чек.', pot:12}], question:'Что делаешь с AJ против стационарного BB?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'value vs station', explain:'Стационер коллит широко — AJ на тёрне продолжает бареллить по ценности и защите.', difficulty:1, tags:['соперник','стационер','тёрн'] }),
  T({ id:'OPP_MANIAC_3BARREL', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'36 LEFT', position:'BB', hero:['A♥','9♣'], heroStack:35, villain:'BTN', villainStack:32, opp:'МАНИАК', board:['Q♦','J♣','7♠','4♥','2♣'], pot:26, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BB чек, BTN 70%, BB колл.', pot:12},{street:'ТЁРН', text:'BB чек, BTN 80%, BB колл.', pot:24},{street:'РИВЕР', text:'BTN ставит 100% банка.', pot:26}], question:'Что делаешь с A-high против тройного бареля маниака?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'bluffcatch maniac', explain:'Маниак переблефовывает: A-high на ривере после его тройного бареля — пограничный, но коллируемый блеф-кетч.', difficulty:3, tags:['соперник','маниак','блеф-кетч'] }),
  T({ id:'OPP_AGRO_CHECK', street:'ТЁРН', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'31 LEFT', position:'BTN', hero:['T♠','T♦'], heroStack:44, villain:'BB', villainStack:41, opp:'АГРО-РЕГ', board:['Q♦','9♣','5♠','3♥'], pot:11, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.6},{street:'ФЛОП', text:'check-check.', pot:5.6},{street:'ТЁРН', text:'BB ставит 70%.', pot:11}], question:'Что делаешь с TT против донка агрессивного рега?', options:['ФОЛД','КОЛЛ','РЕЙЗ'], correct:'КОЛЛ', alsoOk:[], concept:'vs donk', explain:'TT на Q953 против донка — топ-пара ниже дамы. Колл держит диапазон, рейз раздувает банк против агрессора.', difficulty:2, tags:['соперник','агрессивный рег','тёрн'] }),
  T({ id:'OPP_LOVER_RIVER', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'38 LEFT', position:'BTN', hero:['Q♦','J♥'], heroStack:40, villain:'BB', villainStack:38, opp:'ЛЮБИТЕЛЬ', board:['Q♣','9♦','5♠','2♥','7♣'], pot:18, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:10},{street:'ТЁРН', text:'BTN 60%, BB колл.', pot:18},{street:'РИВЕР', text:'BB чек.', pot:18}], question:'Что делаешь с QJ против любителя на ривере?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'value vs lover', explain:'Любитель недополовинит с слабыми дамами — ставка на ривере добирает с Qx и пар.', difficulty:2, tags:['соперник','любитель','ривер'] }),

  /* ============ ФОРМАТЫ · СНГ / 3-МАКС / ХА ============ */
  T({ id:'SNG_BUBBLE_AT', street:'ПРЕФЛОП', format:'SNG', blinds:[300,600], ante:60, stage:'БАББЛ', table:'3-MAX', left:'3 LEFT', position:'BTN', hero:['A♠','T♠'], heroStack:22, villain:'BB', villainStack:24, opp:'РЕГ', board:[], pot:2.4, history:[{street:'ПРЕФЛОП', text:'SNG, баббл: 3 left, призовых 2. BTN открывает.', pot:2.4}], question:'Что делаешь с ATo на баббле 3-макс?', options:['РЕЙЗ','ОЛЛ-ИН'], correct:'РЕЙЗ', alsoOk:[], concept:'SNG bubble', explain:'В СНГ на баббле 3-макс стил очень ценен, но лишняя дисперсия дорога. ATo — оупен-рейз.', difficulty:2, tags:['снг','баббл','3-макс'] }),
  T({ id:'HU_PREFLOP_QQ', street:'ПРЕФЛОП', format:'HU', blinds:[100,200], ante:0, stage:'СРЕДНЯЯ', table:'HU', left:'2 LEFT', position:'BTN', hero:['Q♥','Q♣'], heroStack:60, villain:'BB', villainStack:58, opp:'РЕГ', board:[], pot:6.4, history:[{street:'ПРЕФЛОП', text:'ХА. BTN открыл 2.5, BB 3-бетил 8 ББ.', pot:6.4}], question:'Что делаешь с QQ против 3-бета в ХА?', options:['КОЛЛ','4-БЕТ'], correct:'4-БЕТ', alsoOk:['КОЛЛ'], concept:'HU 4-bet', explain:'В ХА диапазоны шире; QQ против 3-бета — 4-бет по ценности, иногда колл против тайта.', difficulty:1, tags:['ха','QQ','4-бет'] }),
  T({ id:'3MAX_SB_88', street:'ПРЕФЛОП', format:'3MAX', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'3-MAX', left:'3 LEFT', position:'SB', hero:['8♠','8♦'], heroStack:35, villain:'BB', villainStack:33, opp:'РЕГ', board:[], pot:3.4, history:[{street:'ПРЕФЛОП', text:'3-макс. BTN фолд, до тебя один соперник.', pot:3.4}], question:'Что делаешь с 88 в SB 3-макс?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'3-max SB', explain:'В 3-максе диапазоны шире; 88 в SB против BB — обычный оупен, премия за позицию.', difficulty:1, tags:['3-макс','пары','SB'] }),
  T({ id:'SNG_SHORT_AT', street:'ПРЕФЛОП', format:'SNG', blinds:[200,400], ante:50, stage:'ПОЗДНЯЯ', table:'3-MAX', left:'3 LEFT', position:'BTN', hero:['A♠','T♣'], heroStack:11, villain:'BB', villainStack:30, opp:'РЕГ', board:[], pot:1.5, history:[{street:'ПРЕФЛОП', text:'СНГ. 3 left. BTN открывает при 11 ББ.', pot:1.5}], question:'Что делаешь с ATo в BTN при 11 ББ в СНГ?', options:['ОЛЛ-ИН','РЕЙЗ'], correct:'ОЛЛ-ИН', alsoOk:['РЕЙЗ'], concept:'SNG short push', explain:'В СНГ с 11 ББ на батоне ATo — пуш: доминируем и изолируем короткий стек BB.', difficulty:2, tags:['снг','короткий стек','пуш'] }),

  /* ============ РАЗНЫЕ УЛИЦЫ / КОМБО ============ */
  T({ id:'PRE_3B_SQZ_A5S', street:'ПРЕФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'48 LEFT', position:'SB', hero:['A♣','5♣'], heroStack:60, villain:'BTN', villainStack:35, opp:'РЕГ', board:[], pot:12, history:[{street:'ПРЕФЛОП', text:'CO открыл 2.2, BTN заколлил, до тебя.', pot:12}], question:'Что делаешь с A5s в SB со сквизом?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'3-БЕТ', alsoOk:[], concept:'squeeze bluff', explain:'A5s блокирует AA/AK/KK и отлично подходит для сквиза-блефа против двух оппонентов.', difficulty:2, tags:['префлоп','сквиз','блеф'] }),
  T({ id:'PRE_BB_VS_3X', street:'ПРЕФЛОП', format:'MTT', blinds:[1000,2000], ante:250, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'30 LEFT', position:'BB', hero:['7♣','6♣'], heroStack:40, villain:'BTN', villainStack:38, opp:'РЕГ', board:[], pot:8.0, history:[{street:'ПРЕФЛОП', text:'BTN открыл 3.5 ББ, SB сфолдил.', pot:8.0}], question:'Что делаешь с 76s в BB против 3.5x?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'BB vs 3x', explain:'76s против 3.5x защищается реже: цена колла выше, реализация хуже. Фолд.', difficulty:2, tags:['префлоп','защита BB','коннекторы'] }),
  T({ id:'PRE_RFI_SB_KT', street:'ПРЕФЛОП', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'47 LEFT', position:'SB', hero:['K♣','T♣'], heroStack:55, villain:'BB', villainStack:52, opp:'РЕГ', board:[], pot:4.2, history:[{street:'ПРЕФЛОП', text:'Все до SB сфолдили.', pot:4.2}], question:'Что делаешь с KTs в SB?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'RFI SB', explain:'KTs — сильная масть; оупен из SB против BB — стандарт, BB защищается шире в ХА-подобной ситуации.', difficulty:1, tags:['префлоп','RFI','SB'] }),
  T({ id:'T_VALUE_TWO', street:'ТЁРН', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'40 LEFT', position:'BTN', hero:['A♥','Q♦'], heroStack:39, villain:'BB', villainStack:37, opp:'РЕГ', board:['Q♣','8♠','3♦','2♥'], pot:10, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:10},{street:'ТЁРН', text:'BB чек.', pot:10}], question:'Что делаешь с топ-парой AQ на тёрне?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'turn value', explain:'Топ-пара с хорошим кикером продолжает бареллить на безопасном тёрне: BB держит пары и дрова.', difficulty:1, tags:['тёрн','ценность','топ-пара'] }),
  T({ id:'R_TRIP_PAIRED', street:'РИВЕР', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'38 LEFT', position:'CO', hero:['A♠','Q♠'], heroStack:41, villain:'BB', villainStack:38, opp:'РЕГ', board:['A♦','K♣','7♠','3♥','3♠'], pot:20, history:[{street:'ПРЕФЛОП', text:'CO открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'CO 40%, BB колл.', pot:12},{street:'ТЁРН', text:'CO 60%, BB колл.', pot:20},{street:'РИВЕР', text:'BB чек.', pot:20}], question:'Что делаешь с AQ на ривере AK733?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'river two pair', explain:'AQ с топ-парой и кикером: спаренная доска усиливает наши пары, BB редко лучше. Тонкое значение.', difficulty:2, tags:['ривер','ценность','спаренная доска'] }),
  T({ id:'F_CEBET_OVERPAIR', street:'ФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'33 LEFT', position:'BTN', hero:['K♥','K♣'], heroStack:46, villain:'BB', villainStack:43, opp:'РЕГ', board:['J♠','8♣','4♥'], pot:5.6, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BB чек.', pot:5.6}], question:'Что делаешь с KK на флопе J84?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'c-bet overpair', explain:'KK — оверпара выше J84. С-бет собирает ценность с пар и дров, доска не слишком динамична.', difficulty:1, tags:['флоп','с-бет','оверпара'] }),

  /* ============ ПРОДВИНУТЫЕ · PKO / ICM / финальный стол ============ */
  T({ id:'TOUR_PKO_BUBBLE_99', street:'ПРЕФЛОП', format:'PKO', blinds:[800,1600], ante:200, stage:'БАББЛ', table:'6-MAX', left:'10 LEFT', position:'BB', hero:['9♥','9♠'], heroStack:20, villain:'BTN', villainStack:30, opp:'РЕГ', board:[], pot:7.0, history:[{street:'ПРЕФЛОП', text:'PKO, баббл. BTN с баунти открыл 2.2 ББ, SB сфолдил.', pot:7.0}], question:'Что делаешь с 99 в BB на баббле PKO против баунти?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'КОЛЛ', alsoOk:['3-БЕТ'], concept:'PKO bubble defend', explain:'На баббле PKO короткие стеки реже рискуют, но 99 в BB против оупена — защита коллом с сет-потенциалом.', difficulty:2, tags:['PKO','баббл','пары'] }),
  T({ id:'TOUR_PKO_FT_TT', street:'ПРЕФЛОП', format:'PKO', blinds:[1500,3000], ante:400, stage:'ФИНАЛЬНЫЙ СТОЛ', table:'9-MAX', left:'6 LEFT', position:'SB', hero:['T♠','T♦'], heroStack:22, villain:'BB', villainStack:60, opp:'АГРО-РЕГ', board:[], pot:2.7, history:[{street:'ПРЕФЛОП', text:'PKO, финальный стол, 6 left. Все до SB сфолдили.', pot:2.7}], question:'Что делаешь с TT в SB при 22 ББ на финальном столе PKO?', options:['РЕЙЗ','ОЛЛ-ИН'], correct:'ОЛЛ-ИН', alsoOk:['РЕЙЗ'], concept:'final table PKO shove', explain:'При 22 ББ TT — сильная рука для пуша из SB: доминируем большинство колл-диапазона и собираем анте.', difficulty:2, tags:['PKO','финальный стол','пуш'] }),
  T({ id:'TOUR_PKO_COVER_JJ', street:'ПРЕФЛОП', format:'PKO', blinds:[1000,2000], ante:250, stage:'ITM', table:'6-MAX', left:'14 LEFT', position:'BB', hero:['J♦','J♣'], heroStack:32, villain:'BTN', villainStack:33, opp:'РЕГ', board:[], pot:7.7, history:[{street:'ПРЕФЛОП', text:'PKO, ITM. BTN открыл, ты 3-бетил, BTN с баунти запушил олл-ин на 33 ББ.', pot:7.7}], question:'Что делаешь с JJ против баунти-пуша, покрывая соперника?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'PKO cover call', explain:'Покрывая баунти, за каждого снятого игрока получаешь полный баунти. JJ против пуша BTN — прибыльный колл.', difficulty:2, tags:['PKO','баунти','покрытие'] }),
  T({ id:'TOUR_ICM_QQ_FT', street:'ПРЕФЛОП', format:'MTT', blinds:[1200,2400], ante:300, stage:'ФИНАЛЬНЫЙ СТОЛ', table:'6-MAX', left:'6 LEFT', position:'BB', hero:['Q♠','Q♦'], heroStack:30, villain:'CO', villainStack:70, opp:'РЕГ', board:[], pot:9.0, history:[{street:'ПРЕФЛОП', text:'Финальный стол. CO открыл, ты 3-бетил, CO запушил олл-ин на 70 ББ.', pot:9.0}], question:'Что делаешь с QQ на финальном столе против пуша чиплидера?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'final table ICM QQ', explain:'QQ — слишком сильная рука, чтобы фолдить на ICM: колл доминирует много пушащих рук, дисперсия оправдана.', difficulty:2, tags:['финальный стол','ICM','QQ'] }),
  T({ id:'TOUR_ICM_AJ_FOLD', street:'ПРЕФЛОП', format:'MTT', blinds:[2000,4000], ante:500, stage:'ФИНАЛЬНЫЙ СТОЛ', table:'6-MAX', left:'4 LEFT', position:'BB', hero:['A♦','J♠'], heroStack:14, villain:'BTN', villainStack:75, opp:'АГРО-РЕГ', board:[], pot:12.5, history:[{street:'ПРЕФЛОП', text:'Финальный стол, 4 left. BTN запушил олл-ин на 75 ББ.', pot:12.5}], question:'Что делаешь с AJo на финальном столе против пуша чиплидера?', options:['ФОЛД','КОЛЛ'], correct:'ФОЛД', alsoOk:[], concept:'final table ICM fold', explain:'AJo против пуша 75 ББ при 4 left на финальном столе — ICM-фолд: доминируемая рука, высокий риск вылета.', difficulty:3, tags:['финальный стол','ICM','фолд'] }),
  T({ id:'TOUR_BUBBLE_AT_CALL', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'БАББЛ', table:'6-MAX', left:'9 LEFT', position:'BB', hero:['A♣','T♠'], heroStack:20, villain:'SB', villainStack:25, opp:'РЕГ', board:[], pot:6.0, history:[{street:'ПРЕФЛОП', text:'Баббл, 9 left. SB запушил олл-ин на 25 ББ.', pot:6.0}], question:'Что делаешь с ATo в BB на баббле против пуша из SB?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'bubble call AT', explain:'На баббле SB пуш-диапазон шире, но ATo — сильная рука: против пуша SB из блайндов колл прибыльный.', difficulty:2, tags:['баббл','колл','AT'] }),

  /* ============ ПРОДВИНУТЫЕ · кэш и глубокие стеки ============ */
  T({ id:'CASH_3BET_AA_DRAWY', street:'ФЛОП', format:'CASH', blinds:[5,10], ante:0, stage:'СРЕДНЯЯ', table:'6-MAX', left:'6 СТЕКОВ', position:'BB', hero:['A♠','A♥'], heroStack:100, villain:'BTN', villainStack:100, opp:'РЕГ', board:['K♥','J♠','9♦'], pot:62, history:[{street:'ПРЕФЛОП', text:'BTN открыл 2.5, BB 3-бетил 8 ББ, BTN заколлил.', pot:62},{street:'ФЛОП', text:'BTN чек.', pot:62}], question:'Что делаешь с AA в 3-бет-поте на координатной доске KJ9?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'3bet pot overpair', explain:'AA — оверпара, но на KJ9 много дров (QT, T8). Ставка в 3-бет-поте добирает и защищает.', difficulty:2, tags:['кэш','3-бет-пот','AA'] }),
  T({ id:'CASH_DEEP_KK_4B', street:'ПРЕФЛОП', format:'CASH', blinds:[5,10], ante:0, stage:'СРЕДНЯЯ', table:'6-MAX', left:'6 СТЕКОВ', position:'BTN', hero:['K♦','K♣'], heroStack:200, villain:'BB', villainStack:250, opp:'РЕГ', board:[], pot:70, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB 3-бетил, BTN 4-бетил, BB запушил 5-бет олл-ин на 250 ББ.', pot:70}], question:'Что делаешь с KK на глубоких стеках против 5-бет-пуша?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'deep 5-bet call', explain:'KK на 200 ББ — 5-бет-пуш почти всегда AA или разнобой с AK. Колл оправдан: слишком много блефов и доминация AK.', difficulty:2, tags:['кэш','KK','глубокий стек'] }),
  T({ id:'CASH_SQZ_AK', street:'ПРЕФЛОП', format:'CASH', blinds:[10,20], ante:0, stage:'СРЕДНЯЯ', table:'9-MAX', left:'9 СТЕКОВ', position:'SB', hero:['A♠','K♠'], heroStack:100, villain:'CO', villainStack:60, opp:'РЕГ', board:[], pot:60, history:[{street:'ПРЕФЛОП', text:'CO открыл 3 ББ, BTN заколлил, до тебя в SB.', pot:60}], question:'Что делаешь с AKs в SB при сквизе в кэше?', options:['ФОЛД','КОЛЛ','3-БЕТ'], correct:'3-БЕТ', alsoOk:[], concept:'cash squeeze AK', explain:'AKs — сильный сквиз из SB: блокирует тузы и королей, доминирует диапазоны коллера и опенера.', difficulty:1, tags:['кэш','сквиз','AK'] }),
  T({ id:'SNG_ICM_77', street:'ПРЕФЛОП', format:'SNG', blinds:[300,600], ante:60, stage:'БАББЛ', table:'3-MAX', left:'3 LEFT', position:'BB', hero:['7♠','7♥'], heroStack:25, villain:'BTN', villainStack:26, opp:'РЕГ', board:[], pot:5.0, history:[{street:'ПРЕФЛОП', text:'СНГ, баббл 3-макс. BTN запушил олл-ин на 26 ББ.', pot:5.0}], question:'Что делаешь с 77 в BB на баббле СНГ против пуша?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'SNG bubble call', explain:'В СНГ 3-макс на баббле пуши широкие. 77 против BTN-пуша — колл с сет-потенциалом и доминацией пар.', difficulty:2, tags:['снг','баббл','пары'] }),

  /* ============ ПРОДВИНУТЫЕ · 3-бет-пот постфлоп ============ */
  T({ id:'F_3BET_JJ_SCARY', street:'ФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'34 LEFT', position:'BB', hero:['J♣','J♦'], heroStack:62, villain:'BTN', villainStack:59, opp:'РЕГ', board:['A♣','K♦','4♥'], pot:24, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB 3-бетил, BTN заколлил.', pot:24},{street:'ФЛОП', text:'BTN чек.', pot:24}], question:'Что делаешь с JJ в 3-бет-поте на доске AK4?', options:['ЧЕК','СТАВКА'], correct:'ЧЕК', alsoOk:[], concept:'3bet pot overpair check', explain:'JJ на AK4 в 3-бет-поте — низко в диапазоне: ставка превращает руку в блеф. Чек-бек контролирует банк.', difficulty:2, tags:['3-бет-пот','оверпара','чек'] }),
  T({ id:'T_3BET_BLUF', street:'ТЁРН', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'31 LEFT', position:'BTN', hero:['8♠','7♠'], heroStack:55, villain:'BB', villainStack:52, opp:'АГРО-РЕГ', board:['J♠','9♣','4♠','5♦'], pot:28, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB 3-бетил, BTN заколлил.', pot:20},{street:'ФЛОП', text:'BB чек, BTN 50%, BB колл.', pot:28},{street:'ТЁРН', text:'BB чек.', pot:28}], question:'Что делаешь с 87s и флаш-дро на тёрне в 3-бет-поте?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'3bet pot turn semibluff', explain:'87s с флаш-дро и гатшотом — сильная полублеф-рука: ставим на тёрне, имея много аутов и фолд-эквити.', difficulty:3, tags:['3-бет-пот','тёрн','полублеф'] }),

  /* ============ ПРОДВИНУТЫЕ · многосторонние банки ============ */
  T({ id:'F_MULTIWAY_TP', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'44 LEFT', position:'BTN', hero:['A♦','Q♠'], heroStack:48, villain:'BB', villainStack:50, opp:'РЕГ', board:['A♠','9♣','6♦'], pot:9.0, history:[{street:'ПРЕФЛОП', text:'CO открыл, BTN заколлил, BB заколлил.', pot:9.0},{street:'ФЛОП', text:'Все проверяют до тебя.', pot:9.0}], question:'Что делаешь с AQ в многостороннем банке на флопе A96?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'multiway c-bet', explain:'AQ — топ-пара в 3-уэй поту: ставка собирает ценность с худших пар и дров, пока ты в позиции.', difficulty:2, tags:['многосторонний','флоп','топ-пара'] }),
  T({ id:'F_SQUEEZE_SET', street:'ФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'6-MAX', left:'32 LEFT', position:'BB', hero:['8♣','8♦'], heroStack:55, villain:'BTN', villainStack:48, opp:'РЕГ', board:['K♥','8♠','2♦'], pot:30, history:[{street:'ПРЕФЛОП', text:'CO открыл, BTN заколлил, BB запушил сквиз, оба заколлили.', pot:30},{street:'ФЛОП', text:'BTN ставит 60% банка.', pot:30}], question:'Что делаешь с сетом в сквизнутой поте против ставки?', options:['КОЛЛ','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'squeezed pot set', explain:'Сет в большом поту — монстр. Чек-рейз на флопе раздувает банк и добирает с пар и дров.', difficulty:2, tags:['сквиз-пот','сет','чек-рейз'] }),

  /* ============ ПРОДВИНУТЫЕ · постфлоп и позиции ============ */
  T({ id:'F_AA_COORD', street:'ФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'40 LEFT', position:'BTN', hero:['A♥','A♣'], heroStack:45, villain:'BB', villainStack:42, opp:'РЕГ', board:['Q♦','J♠','7♣'], pot:5.4, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BB чек.', pot:5.4}], question:'Что делаешь с AA на координатной доске QJ7?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'overpair coordinated', explain:'AA — оверпара, но на QJ7 есть стрит- и флаш-дро. Ставка на флопе защищает и добирает.', difficulty:1, tags:['флоп','AA','оверпара'] }),
  T({ id:'T_BARREL_BLUF', street:'ТЁРН', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'38 LEFT', position:'BTN', hero:['7♥','8♥'], heroStack:40, villain:'BB', villainStack:38, opp:'РЕГ', board:['K♣','9♠','3♦','5♥'], pot:11, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:11},{street:'ТЁРН', text:'BB чек.', pot:11}], question:'Что делаешь с 78s и гатшотом на тёрне?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'turn barrel bluff', explain:'78s с гатшотом (T/J) и бэкдором — кандидат на второй баррель: много аутов и фолд-эквити против пар.', difficulty:2, tags:['тёрн','блеф','гатшот'] }),
  T({ id:'R_VALUE_TPTK', street:'РИВЕР', format:'MTT', blinds:[600,1200], ante:150, stage:'СРЕДНЯЯ', table:'6-MAX', left:'36 LEFT', position:'BTN', hero:['A♠','K♠'], heroStack:42, villain:'BB', villainStack:39, opp:'РЕГ', board:['A♦','Q♣','8♠','4♥','2♣'], pot:18, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:5.2},{street:'ФЛОП', text:'BTN 40%, BB колл.', pot:12},{street:'ТЁРН', text:'BTN 60%, BB колл.', pot:18},{street:'РИВЕР', text:'BB чек.', pot:18}], question:'Что делаешь с топ-парой AK на ривере?', options:['ЧЕК','СТАВКА'], correct:'СТАВКА', alsoOk:[], concept:'river TPTK value', explain:'AK — топ-пара с топ-кикером на сухом ривере. Ставка добирает с худших Ax и пар — классическое тонкое значение.', difficulty:1, tags:['ривер','ценность','топ-пара'] }),
  T({ id:'R_BLUF_CATCH_PRICE', street:'РИВЕР', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'37 LEFT', position:'BB', hero:['T♥','T♣'], heroStack:36, villain:'BTN', villainStack:34, opp:'АГРО-РЕГ', board:['Q♦','9♠','4♣','3♥','6♦'], pot:20, history:[{street:'ПРЕФЛОП', text:'BTN открыл, BB заколлил.', pot:4.7},{street:'ФЛОП', text:'check-check.', pot:4.7},{street:'ТЁРН', text:'BB ставит 50%, BTN колл.', pot:11},{street:'РИВЕР', text:'BTN ставит 40% банка.', pot:20}], question:'Что делаешь с TT против маленькой ставки на ривере?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'river price bluffcatch', explain:'TT — средняя пара на ривере. Маленький размер даёт отличную цену против агрессивного рега — колл-кетч.', difficulty:2, tags:['ривер','блеф-кетч','цена'] }),
  T({ id:'PRE_RFI_UTG_99', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'СРЕДНЯЯ', table:'9-MAX', left:'54 LEFT', position:'UTG', hero:['9♣','9♦'], heroStack:58, villain:'BB', villainStack:55, opp:'РЕГ', board:[], pot:6.6, history:[{street:'ПРЕФЛОП', text:'Ты первый в раздаче.', pot:6.6}], question:'Что делаешь с 99 в UTG?', options:['ФОЛД','РЕЙЗ'], correct:'РЕЙЗ', alsoOk:[], concept:'RFI UTG pairs', explain:'99 — открываемая рука из ранней позиции на глубоких стеках: сильная пара, реализует сет-ценность.', difficulty:1, tags:['префлоп','RFI','ранняя позиция'] }),
  T({ id:'PRE_BB_VS_SQZ', street:'ПРЕФЛОП', format:'MTT', blinds:[500,1000], ante:125, stage:'СРЕДНЯЯ', table:'6-MAX', left:'45 LEFT', position:'BB', hero:['8♥','7♥'], heroStack:45, villain:'SB', villainStack:30, opp:'АГРО-РЕГ', board:[], pot:11.5, history:[{street:'ПРЕФЛОП', text:'BTN открыл, SB с коротким стеком запушил сквиз 30 ББ, BTN сфолдил.', pot:11.5}], question:'Что делаешь с 87s в BB против сквиз-пуша?', options:['ФОЛД','КОЛЛ'], correct:'КОЛЛ', alsoOk:[], concept:'BB vs squeeze', explain:'87s в BB против сквиз-пуша при хорошей цене и блокерах на стрит — защита коллом с потенциалом.', difficulty:2, tags:['префлоп','сквиз','коннекторы'] }),
  T({ id:'PRE_4BET_AA_COLD', street:'ПРЕФЛОП', format:'MTT', blinds:[800,1600], ante:200, stage:'ПОЗДНЯЯ', table:'6-MAX', left:'25 LEFT', position:'CO', hero:['A♠','A♦'], heroStack:90, villain:'BTN', villainStack:85, opp:'АГРО-РЕГ', board:[], pot:14, history:[{street:'ПРЕФЛОП', text:'UTG открыл, ты заколлил, BTN 3-бетил 10 ББ, UTG сфолдил.', pot:14}], question:'Что делаешь с AA против колд-3-бета на баттоне?', options:['КОЛЛ','4-БЕТ'], correct:'4-БЕТ', alsoOk:[], concept:'cold 4-bet', explain:'AA против колд-3-бета — 4-бет по ценности: раздуваем банк против сильного, но более узкого диапазона BTN.', difficulty:1, tags:['префлоп','4-бет','AA'] }),

  ...ADVANCED_TASKS,
  ...ADVANCED_TASKS_9B
];

export function buildLibrary() {
  return TASKS.map(t => Object.assign({}, emptyTask(), t));
}